/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.practice;

import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;
import java.util.function.*;

public class App {
    public String getGreeting(String args) {
        System.out.println("Aadavan here how are you appa?");
        return args + "\tHello World!";
    }

    public static void main(String[] args) {
        String value = (args != null && args.length > 0) ? args[0] : "Aadavan";
        //System.out.println(new App().getGreeting(value));
        Predicate<String> name = Objects::nonNull;
        name = name.or(s -> s.startsWith("A"));
        name = name.and(s -> s.length() > 5);

        List<String> names = Arrays.asList("Aadavan", "Mahesh");
        List<String> collect = names.stream().filter(name).collect(Collectors.toList());
        collect.forEach(System.out::println);
    }

}
